[package]
name = "neat"
version = "0.1.0"
authors = ["Phlopsi <nbphobos@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
rustc-hash = "*"
arraydeque = "*"
